const CONFIG = {
    API_URL: 'https://absensi-api.yumenoboken.workers.dev',
    GOOGLE_CLIENT_ID: '103167988388-j5j4o83ieakv5o4rakv1v735btgp3ldp.apps.googleusercontent.com',
    SUPER_ADMIN_EMAILS: ['lpkinsanjaya@gmail.com', 'yumenoboken@gmail.com', 'najwanhp123@gmail.com'],
    ADMIN_EMAILS: ['lpkinsanjaya@gmail.com', 'yumenoboken@gmail.com', 'elsasidamawarniut@gmail.com', 'zilisaje@gmail.com', 'calonmaou@gmail.com'],
    GURU_EMAILS: [
        'lpkinsanjaya@gmail.com',
        'yumenoboken@gmail.com',
        'mlbb080106@gmail.com',
        'tzaharasyaputri@gmail.com',
        'usniatun25@gmail.com',
        'ayunurhasanah1707@gmail.com',
        'shintadeslianty@gmail.com',
        'uthiuthi1130@gmail.com',
        'elsasidamawarniut@gmail.com',
        'zilisaje@gmail.com',
        'calonmaou@gmail.com',
        'novadamayanti850@gmail.com',
        'salwamansyur@gmail.com',
        'ildanazila15@gmail.com',
        'gustianimeli970@gmail.com',
    ],
    CLASSES_BY_PROGRAM: {
        "Program 1 Bulan": ["Reguler", "Kelas Pagi", "Kelas Siang", "Kelas Sore"],
        "Program 3 Bulan": ["Reguler", "Kelas Pagi", "Kelas Siang", "Kelas Sore"],
        "Program 6 Bulan": ["Reguler", "Kelas Pagi", "Kelas Siang", "Kelas Sore"],
        "Program Private": ["Private 1-on-1", "Private Grup"],
        "bimbel": ["Kelas 1", "Kelas 2", "Kelas 3", "Kelas 4", "Kelas 5", "Kelas 6", "Kelas 7", "Kelas 8", "Kelas 9"],
        "bahasa inggris": ["Beginner", "Intermediate", "Upper Intermediate", "Advanced"],
        "bahasa arab": ["Iqra + B Arab Dasar"],
        "komputer": ["SD", "SMP", "SMA"],
        "calistung": ["Baca + Tulis + Hitung"],
        "menggambar & mewarnai": ["Gambar + Warna"]
    },
    GURU_BY_PROGRAM: {
        "Program 1 Bulan": ["Instruktur LKP Zakiyah", "Shinta Deslianty, S.Pd", "Usniatun Sudiarsih, SH", "Meli Gustiani"],
        "Program 3 Bulan": ["Instruktur LKP Zakiyah", "Shinta Deslianty, S.Pd", "Usniatun Sudiarsih, SH", "Meli Gustiani"],
        "Program 6 Bulan": ["Instruktur LKP Zakiyah", "Shinta Deslianty, S.Pd", "Usniatun Sudiarsih, SH", "Meli Gustiani"],
        "Program Private": ["Instruktur LKP Zakiyah", "Shinta Deslianty, S.Pd", "Usniatun Sudiarsih, SH", "Meli Gustiani"],
        "bimbel": ["Shinta Deslianty, S.Pd", "Usniatun Sudiarsih, SH", "Meli Gustiani", "Ildatun Nazila S.E"],
        "bahasa inggris": ["Tri Zahara, S.Pd", "Wasaluwa"],
        "calistung": ["Usniatun Sudiarsih, SH"],
        "bahasa arab": ["Ayu Nurhasanah, S.Sos"],
        "komputer": ["Nova Damayanti"],
        "menggambar & mewarnai": ["Futria Tamasari S.Hum"]
    }
};
